title: Stop Targeting Ads at Me
tagline_part_one: Helps you turn off targeted ads on
tagline_part_two: websites, apps, services, and devices
# The current number of sites goes between these two parts above on the frontend. (This file is completely static.)
description: >- # this means to ignore newlines
  Advertisers use data about what you do and who you are to target ads at you. Start turning off this targeted advertising.
url: "https://stoptargetingads.me"

# Header nav (remember the trailing /)
navigation_header:
  Home: /
  About: /about/

# Build settings
markdown: kramdown
# plugins:
#   - jekyll-feed

collections:
  items:
    output: true
    permalink: :name

defaults:
  - scope:
      path: ""
      type: "items"
    values:
      layout: item_page

# Tell Jekyll to use the _headers file for security headers
include:
  - _headers

# If an Atom/RSS feed is useful
# feed:
#   collections:
#     - items

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/
