backend:
  name: git-gateway
  branch: master # Branch to update (optional; defaults to master)
  commit_messages:
    create: Create {{collection}} "{{slug}}"
    update: Update {{collection}} "{{slug}}"
    delete: Delete {{collection}} "{{slug}}"
    uploadMedia: Upload "{{path}}"
    deleteMedia: Delete "{{path}}"

media_folder: "images/logos"

collections:
  - name: "item"
    label: "Items"
    singular_label: "Item"
    folder: "_items"
    create: true
    slug: "{{slug}}" # Filename template, e.g., YYYY-MM-DD-title.md
    fields: # The fields for each document, usually in front matter
      - {label: "Name", name: "name", widget: "string", description: "The name or names of the company"}

      - label: "Links"
        name: "link"
        widget: "list"
        description: "Link(s) to the opt out page(s) for that organisation"
        required: false
        field: {label: Link, name: link, widget: string}

      - label: "Logo"
        name: "logo"
        widget: "image"
        default: "images/site/default_logo.png"
        description: "The company logo"

        media_library:
          config:
            multiple: false
      - {label: "Body", name: "body", widget: "markdown"}
